---
- name: Ensure Ubuntu system is updated
  hosts: ubuntu-server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Reboot if required
      reboot:
        reboot_timeout: 600
        test_command: whoami
      when: ansible_facts['pkg_mgr'] == 'apt'
